//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TennisDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlayerResult
    {
        public int Id { get; set; }
        public Nullable<int> PlayerId { get; set; }
        public Nullable<int> MatchId { get; set; }
        public Nullable<int> FirstSet { get; set; }
        public Nullable<int> SecondSet { get; set; }
        public Nullable<int> ThirdSet { get; set; }
        public Nullable<int> OutcomeId { get; set; }
    
        public virtual Match Match { get; set; }
        public virtual Outcome Outcome { get; set; }
        public virtual Player Player { get; set; }
    }
}
