//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TennisDb
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TennisEntities : DbContext
    {
        public TennisEntities()
            : base("name=TennisEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Match> Matches { get; set; }
        public virtual DbSet<Outcome> Outcomes { get; set; }
        public virtual DbSet<Player> Players { get; set; }
        public virtual DbSet<PlayerResult> PlayerResults { get; set; }
        public virtual DbSet<Surface> Surfaces { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
